---
dependency:
  name: galaxy
driver:
  name: ${DRIVER_NAME:-podman}
platforms:
  - name: foreman.example.com
    image: quay.io/centos/centos:stream9
    hostname: foreman.example.com
    command: /sbin/init
provisioner:
  name: ansible
verifier:
  name: ansible
