---
- name: Prepare
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Configure Puppet repositories
      ansible.builtin.include_role:
        name: puppet_repositories
    - name: Configure Foreman repositories
      ansible.builtin.include_role:
        name: foreman_repositories
      vars:
        foreman_repositories_version: "3.10"
        foreman_repositories_katello_version: "4.12"
    - name: Ensure langpacks on EL8
      ansible.builtin.dnf:
        name: glibc-langpack-en
        state: present
      when: ansible_facts['os_family'] == 'RedHat'
    - name: Run installer
      ansible.builtin.include_role:
        name: installer
      vars:
        foreman_installer_scenario: katello
        foreman_installer_package: foreman-installer-katello
        foreman_installer_options:
          - '--tuning development'
