---
dependency:
  name: galaxy
driver:
  name: ${DRIVER_NAME:-podman}
platforms:
  - name: almalinux8
    image: docker.io/almalinux:8
  - name: centos9
    image: quay.io/centos/centos:stream9
provisioner:
  name: ansible
verifier:
  name: ansible
