---
dependency:
  name: galaxy
driver:
  name: ${DRIVER_NAME:-podman}
platforms:
  - name: centos9
    image: quay.io/centos/centos:stream9
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp:exec,mode=777
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
